version: "3.8"
services:
  web:
    image: todo-web-app
    depends_on:
      - todo-api
    ports:
      - "3000:3000"
    networks:
      - network-frontend
  todo-api:
    image: todo-api
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
     - network-frontend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks: 
     - network-backend



networks:
  network-backend:
      driver: bridge
  network-frontend:
      driver: bridge

volumes: 
  mongodb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data'
