version: "3.8"
services:
  web:
    image: yolix/todo-web-app:v1
    depends_on:
      - todo-api
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    networks:
      - network-frontend
  todo-api:
    image: yolix/todo-api:v1
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
     - network-frontend
  
  mongo:
    image: mongo
    restart: always
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks: 
     - network-backend

networks:
  network-backend:
      driver: bridge
  network-frontend:
      driver: bridge

volumes: 
  mongodb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/tmp/data'
