apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: web-app
        image: yolix/todo-web-app:v1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://localhost:3001/api
      - name: web-api
        image: yolix/todo-api:v1
        ports:
        - containerPort: 3001
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          value: username
        - name: MONGODB_INITDB_ROOT_PASSWORD
          value: password
